name: translator
version: 0.1.0+7
description: A free and unlimited Google Translate API for Dart. You can use it for translate strings and text for educational purpose.
author: Gabriel N. Pacheco <gabrielpacheco23@live.com>
homepage: https://github.com/gabrielpacheco23/google-translator
dependencies:
  http:
    git:
      url: git://github.com/jefioliveira/http
      ref: 6d0dcfab711d98b63dfe12f0a2f3d9ee2a7007c5

dev_dependencies:
  test: any

environment:
  #sdk: "2.0.0"
  sdk: ">=2.0.0 <3.0.0"